### PR TITLE
Update to golang:1.16

### PR DESCRIPTION
**Pull request by Bensuperpc**
Update to golang:1.16

Signed-off-by: Bensuperpc <bensuperpc@gmail.com>

### CODE REVIEW

**Comment by itzg** [comment]
The actual build is done via CircleCI, so can you also update

https://github.com/itzg/mc-monitor/blob/master/.circleci/config.yml

**Comment by Bensuperpc** [comment]
> The actual build is done via CircleCI, so can you also update
> 
> https://github.com/itzg/mc-monitor/blob/master/.circleci/config.yml

The file has been updated

**Review by itzg — APPROVED** [review]
Thanks! I'll kick off a release, but might be later today.

**Comment by itzg** [comment]
..and released https://github.com/itzg/mc-monitor/releases/tag/0.9.0

**Pull request merged**
