### PR TITLE
deps: upgrade to Go 1.22.5 to fix vulnerabilities

### PR DESCRIPTION
**Pull request by strausmann**
HIGH: https://pkg.go.dev/vuln/GO-2024-2963

### CODE REVIEW

**Comment by itzg** [comment]
That vulnerability does not affect this application. I run weekly govulncheck's that avoid false negatives and wasted time and effort.

https://github.com/itzg/mc-monitor/actions/runs/9824443576/job/27218087754#step:2:150

**Comment by itzg** [comment]
https://go.dev/blog/vuln

**Comment by strausmann** [comment]
I only ever respond to the poor security rating of my Docker images here.
Here is an example:
image

**Comment by strausmann** [comment]
Renovate automatically builds a new Docker image for me when a dependency has a new release that is intended to solve a CVE.

**Comment by itzg** [comment]
Sorry for taking my frustration out on you. I'll merge this PR and cut a release, but I'm still not happy about the govulncheck vs docker scout thing.

**Comment by strausmann** [comment]
https://git.strausmann.de/minecraft/bedrock-connect/-/blob/main/renovate.json?ref_type=heads

I made this possible with the config. have focused on the configuration of home assistant addons. in my test last week it had worked. tonight I will see if it is detected correctly.

**Comment by strausmann** [comment]
> Sorry to leave my frustration on you. I'm going to merge this PR and cut a release, but I'm still not happy about the Gouverncheck vs. Docker Scout thing.

I can understand that this different test produces unnecessary work.

**Comment by itzg** [comment]
> https://git.strausmann.de/minecraft/bedrock-connect/-/blob/main/renovate.json?ref_type=heads
> 
> 
> 
> I made this possible with the config. have focused on the configuration of home assistant addons. in my test last week it had worked. tonight I will see if it is detected correctly. 

Thanks! That's exactly the customization I was hoping you were using.

**Pull request merged**
